branches:
  only:
  - master
bundler_args: "--without production --deployment --jobs=3 --retry=3"
cache: bundler
env:
  global:
  - secure: T4AIZxay4TOpglXemSwOFQJ7EhJM2408XIj0c0ywFvke/MopkBI2WF4igdnGg2Y5/H9ZClN54aA33CelDgdNaNVF0zN3BfUTkU3Mde61lcxhhGvYGGgwTib8ijUuFcwRtG3iDvk8hULiu028WZ8+KO4LDNYJV8jUqVcLJ7uj3IM=
  - secure: RRsaklwWXa5WqoGw0rxxuCtYYCXd0as7HUL7BonSkPWVBB+vBGRFuau+kngLYFiuivi/fh3a9y72w4pzMm7Il6kJ4SWltO3hi1TQnGs2U8zEbp4UJVspWznI1x2FA67xoNW+qNlx4TP6QKXIsJkd/MNP/2Liw8eMY/QchuA/G5I=
  - secure: f7x+qtGNfmV4CG58B8oBe2tq6P0vADE5mt2Gz9THfdtd7N679Ia0GCQhrDWO7abf/nQ3m9RbEqrERQD03UN4OBcL9qWjoqiAAfZm/mG+g7JjQTQWzAZ7EbXMcwAk0S0PPGkV4rbLoMEMDORZA0TDbShyJSxwEr40CCTmUDesKHc=
  - secure: P3Hzh3B7bCrwCT19RwAGjk7XfUiDkzg19Bw7AKKdh2+bagXRzJe7ISxbiAKpPXR6l+GzRY8YqnSbZa7+NDikXu0SWygJl06Quvn3o3RYU24BX4PEaXWlZbT43YMbaLMPkdGE3+4WEk7iecTkPtVK7xtRffBv3ew/xS3hXhEPtXU=
  - secure: DQkHlK0u/rL7lEMMDLday6TRYPsKJsjAv31tc1imx37DnAqh4mzZomyEx8SOuF5BraT9sk3h7XLj6xa1uCZhdSrBJ0odnWovizJgqdKGNgnFfef8RuZTMArB23vPEmGWyDCeCi8Ha4j53IlSHn6RWpkXCfWpj6HAWaTGksRyYpI=
language: ruby
notifications:
  email: false
rvm:
- 2.4.1
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --disable-external
