name: Brighton Ruby Conference 2015

markdown: kramdown
highlighter: pygments
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
permalink: /:year/:title/

gems:
  - jekyll-redirect-from

collections:
  misc:
    output: true
    permalink: /misc/:path/
