name: Brighton Ruby Conference 2016

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
permalink: /:year/:title/
future: true

sass:
  style: :compressed

collections:
  archives:
    output: true
    permalink: /:path/
    layout: archive
  misc:
    output: true
    permalink: /misc/:path/

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
